### ISSUE TITLE
你这报错不少啊

### ISSUE THREAD

**Issue by Cribug8080** [ecojust/pixi_game#1]
```
3 errors and 364 warnings found.
364 warnings potentially fixable with the `--fix` option.
```

**Comment by Cribug8080** [comment]
不过界面能出来，这个是要做什么？

**Comment by ecojust** [comment]
应该是一些变量pixi对象没有，人为加上去的，然后在ts下就报不是这个类的成员变量了，后来改成在ts里声明这个变量类型为any，就不会出现这些问题了，目前工作有点闲，就本着学习pixi和ts的目的，写个小游戏

**Comment by ecojust** [comment]
<img width="550" alt="WechatIMG30" src="https://user-images.githubusercontent.com/30574854/64349762-128dd680-d02a-11e9-8f9a-e798675dbacf.png">
